# Generated by Django 6.1.1 on 2026-09-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='recruiters.company'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
