# Generated by Django 6.1.1 on 2026-10-02 18:50

import recruiters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_skilltag_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eligible_branches',
            field=models.CharField(blank=True, max_length=300, validators=[recruiters.models.validate_eligible_branches]),
        ),
    ]
