# Generated by Django 6.1.1 on 2026-09-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('board_or_university', models.CharField(blank=True, max_length=200)),
                ('percentage_or_cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year_of_completion', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='students.studentprofile')),
            ],
        ),
    ]
