# Generated by Django 6.1.1 on 2026-09-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
