# Generated by Django 6.1.1 on 2026-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
