# Generated by Django 6.1.1 on 2026-10-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentprofile_resume_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIDS', 'AI & Data Science Engineering'), ('AIML', 'AI/ML Engineering'), ('ENTC', 'Electronics and Telecommunication'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ELECTRICAL', 'Electrical Engineering')], max_length=100),
        ),
    ]
